controller_list:
  - name: "/jackal_hulk/hulk_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints: 
      - joint_6
      - joint_7
      - joint_8
      - joint_9
      - joint_10
      - joint_11
